\subsection{INVOKESPECIAL}
\texttt{INVOKESPECIAL} is used to invoke private methods and constructors.
Before the invoke, the operand stack contains an object reference and arguments to pass to the invoked method. These are consumed by the invoke. The reference is then stored in the local variables followed by parameters. Additionally, a new stack frame with an empty operand stack and a program counter set to $0$, is added to the call stack.
\\\\
$$\inference[INVOKESPECIAL]{
inst(P,mid,pc) = \texttt{INVOKESPECIAL }mid' \semsp 
CP(mid') = pn \semnl \\
ops = (x_0, \ldots, x_n, objr, p_1, \ldots, p_{pn}) \semsp
ops' = (x_0, \ldots, x_{n}) \semnl\\
loc' = [0 \mapsto objr, 1 \mapsto p_{1}, \ldots, pn \mapsto p_{pn}])}
{CP, P \vdash \langle H, (CS, \langle mid, loc, ops, pc \rangle)\rangle \Rightarrow }$$
$$\langle H, (CS, \langle mid, loc, ops', pc \rangle, \langle mid', loc', \epsilon, 0 \rangle)\rangle$$\\\\

%These categories are defined in the Java specification: ``Virtual methods are instance methods that are resolved dynamically. The set includes all public, protected and package-visible instance methods. Private instance methods and all constructors are not virtual methods, but instead are resolved statically during compilation.''~\cite[chap. 4.3.7.6]{java_card_spec}

\subsection{THROW}
\texttt{THROW} describes when an exception is thrown. There are two cases handled, when the \texttt{catch} block is found in the same stack frame as the \texttt{throw}, and when it is found in another stack frame, e.g. its invoker. The \texttt{exceptionLookup} method handles these two cases: If the \texttt{catch} is found in the current stack frame, the program counter is set to the location of the exception handling code, the operand stack is cleared, the $objr$ reference (for the exception object) is pushed back onto the stack and execution continues as per the \jc Virtual Machine v2.2 specification~\cite[JcvmSpec p. 151]{java_card_spec}. If no appropriate handling block is found in the current stack frame, the frame is popped and the stack frame of its invoker is reinstated and the exception rethrown.\\
$$CS = (CS', \langle mid, loc, ops, pc \rangle) \hspace{30px} ops = (x_0, \ldots, x_n, objr)$$\vspace{-10px} \\
$exceptionLookup(P, CS) = $ \vspace{-10px} \\
\[
\begin{cases}
  (CS', \langle mid, loc, (objr), pc' \rangle  & if \hspace{5px} exceptDef(P, mid, pc, objr) = pc' \neq \perp\\
  exceptionLookup(P, CS') & otherwise
\end{cases}
\]

$$\inference[THROW]{
inst(P,mid,pc) = \texttt{THROW} }
{CP, P \vdash \langle H, CS \rangle \Rightarrow \langle H, exceptionLookup(P,CS)\rangle}$$